### ISSUE TITLE
switch to non flashplayer

### ISSUE THREAD

**Issue by czpython** [divio/djangocms-video#1]
is there a possibility to throw the flashplayer and replace it with iframe or something better ?

**Comment by sedrubal** [comment]
:+1:

**Comment by dholbach** [comment]
We are tracking the issue over here as well: https://bugs.launchpad.net/developer-ubuntu-com/+bug/1447722

**Comment by kelvan** [comment]
Any progress on this issue?
Flash will (hopefully) die soon and HTML5 video is already widely supported.

**Comment by roemhildtg** [comment]
:+1:

**Comment by jedie** [comment]
any news?!?

**Comment by FinalAngel** [comment]
Going to work on it the week after next week ;)

**Comment by FinalAngel** [comment]
Current update, will release 1.1.0 soon with fixed assets. Will then move to 2.0.0 where we remodel the addon a bit.

**Comment by FinalAngel** [comment]
done once https://github.com/divio/djangocms-video/pull/21 lands
