### ISSUE TITLE
Support youku

### ISSUE THREAD

**Issue by dholbach** [divio/djangocms-video#13]
We have Chinese content on developer.ubuntu.com and it'd be great if we could embed youku videos, as youtube is blocked in China and youku very popular there.

**Comment by evildmp** [comment]
Does youku use the oEmbed specification? If so, https://github.com/nephila/aldryn-video might be a better way forward, as that application is more up-to-date generally.

Otherwise, we'd need to extend djangocms-video to accommodate more video sources.

**Comment by FinalAngel** [comment]
I hope this will be possible through the changes in 2.0. I'll update here

**Comment by FinalAngel** [comment]
will be possible through: https://github.com/divio/djangocms-video/pull/21
