### ISSUE TITLE
swfobject.min.js no longer exists in `cms/js/libs`

### ISSUE THREAD

**Issue by agconti** [divio/djangocms-video#19]
In the latest version of Django-cms, `v3.3.0`, the `swfobject.min.js` file has been removed from the included `cms/js/lib` static files. Djangocms-video depends on this the file to work, so it needs to be added back in to be compatible.

**Comment by adambrenecki** [comment]
In addition, `cms/swf/player.swf` is also missing, and also required for the plugin to work.

**Comment by FinalAngel** [comment]
Will be fixed in https://github.com/divio/djangocms-video/pull/20
