### ISSUE TITLE
Setting for default template

### ISSUE THREAD

**Issue by mammuth** [divio/djangocms-video#29]
There should be an option to conveniently set the template that is selected by default. 

The filer image plugin is doing it like this:
```
CMSPLUGIN_FILER_IMAGE_STYLE_CHOICES = (
    ('default', 'Default'),
    ('boxed', 'Boxed'),
)
CMSPLUGIN_FILER_IMAGE_DEFAULT_STYLE = 'boxed'
```

It looks like there is currently no way to make someones template the default template, is this correct?

**Comment by FinalAngel** [comment]
@mammuth this is correct, the current "default" template is called "default", thats why it's the "default" xD. I'm not too fond of adding another setting to declare the default. Also overriding the "default" might be a problem.

**Comment by FinalAngel** [comment]
We decided not to do tis for now, default should from a UI/UX perspective always be first.

**Comment by mammuth** [comment]
Okay, thanks for thinking about it. 
But when talking about UX, shouldn't it be a goal to have similar behaviors in plugins (so that defining templates should be the same on eg. Filer image and django CMS Video)? 😉

**Comment by mammuth** [comment]
Cool, looking forward to it!

**Comment by afs2015** [comment]
For anyone reading this in the future this is how we got around overriding the default template:

We went into cms_plugins.py for our project and did the following.

from djangocms_video.cms_plugins import VideoPlayerPlugin

class CustomVideoPlugin(VideoPlayerPlugin):
    name = _("Custom Video Player")
    cache = False

    def get_render_template(self, context, instance, placeholder):
        return 'our_video_player.html'

**Comment by Sovetnikov** [comment]
Unusually uncomfortable making plugins added by user to page to stick with Django CMS site custom theme ...

**Comment by Sovetnikov** [comment]
Just to make a custom links bar on a page, i need to make custom plugin instead of just overriding template in placeholder.

Code for djangocms >= 3:

```
from djangocms_link.cms_plugins import LinkPlugin
from django.utils.translation import ugettext_lazy as _
from cms.plugin_pool import plugin_pool

@plugin_pool.register_plugin
class ArticleHeadLinkPlugin(LinkPlugin):
    name = _("Article head link")
    cache = False

    def get_render_template(self, context, instance, placeholder):
        return 'djangocms_link/article_head_link/link.html'
```

This is not related to djangocms-video plugin, but to all djangocms-* plugins series.
