### ISSUE TITLE
Youku

### ISSUE THREAD

**Issue by maltebeckmann** [divio/djangocms-video#30]
I just tried integrating a Youku video into a post using djangocms-video (==2.0.3). I couldn't get it work. Have any of you tried that at all? Does this plugin only work with Youtube and Vimeo? No matter how I amend the embed code url, I just can't get it to show up properly.

**Comment by FinalAngel** [comment]
Hello @maltebeckmann it should work with any video that supports embed, djangocms-video basically renders the video as an iframe. A quick search reveals that you have to use something like:

```http://player.youku.com/player.php/sid/XNDYwMTEzMTY0/v.swf```

**Comment by maltebeckmann** [comment]
Yes, that's the URL format I used. Am I just not posting this correctly: I suppose it needs to be entered in the Embed Video link field. Can you confirm this works for you?

**Comment by FinalAngel** [comment]
@maltebeckmann it seems to be working from a correct link:

http://d.pr/i/wZMf

**Comment by maltebeckmann** [comment]
Ok, I am finally getting a proper error message! First off, thanks for checking that it works!

I am getting a /static/cms/js/libs/swfobject.min.js Failed to load resource: the server responded with a status of 404 (Not Found)

Just out of curiosity, does this swfobject.min.js come packaged with Django-CMS? I did run collectstatic. So I presume I need to download swfobject.min.js manually and place it in the static folder to make this work.

**Comment by FinalAngel** [comment]
@maltebeckmann that is awkward @maltebeckmann swfobject was required in previous versions of djangocms-video. Are you sure you are using >=2.0? The newer versions only use HTML5 video and are not requiring swfobject anywhere.

**Comment by maltebeckmann** [comment]
pip freeze tells me I have djangocms-video==2.0.3

**Comment by maltebeckmann** [comment]
This is the page code that is being generated:

<script type="text/javascript" src="/static/cms/js/libs/swfobject.min.js"></script>

  <script type="text/javascript">//<![CDATA[
    var flashvars = {};
    flashvars.movie = "https://imgcache.qq.com/tencentvideo_v1/playerv3/TPout.swf?max_age=86400&amp;v=20161117&amp;vid=d0364y40wcp&amp;auto=0&quot; allowFullScreen=&quot;true&quot; quality=&quot;high&quot; width=&quot;480&quot; height=&quot;400&quot; align=&quot;middle&quot; allowScriptAccess=&quot;always&quot; type=&quot;application/x-shockwave-flash";
    

    flashvars.autoplay = "false";
    flashvars.loop = "false";
    flashvars.autohide = "false";
    flashvars.fullscreen = "true";

    flashvars.color_text = "0xFFFFFF";
    flashvars.color_seekbar = "0x13ABEC";
    flashvars.color_loadingbar = "0x828282";
    flashvars.color_seekbarbg = "0x333333";

    flashvars.color_button_out = "0x333333";
    flashvars.color_button_over = "0x000000";
    flashvars.color_button_highlight = "0xFFFFFF";

    var params = {};
    params.allowfullscreen = "true";
    params.allowscriptaccess = "always";
    params.bgcolor = "#000000";
    params.wmode = "opaque";

    var attributes = {};
    attributes.align = "middle";

    swfobject.embedSWF("/static/cms/swf/player.swf",
                       "flash-plugin-321",
                       "320", "240",
                       "9", "/static/cms/swf/expressInstall.swf",
                       flashvars, params, attributes);
  //]]></script>

**Comment by FinalAngel** [comment]
@maltebeckmann thats an outdated template, checkout: https://github.com/divio/djangocms-video/tree/master/djangocms_video/templates/djangocms_video/default

**Comment by maltebeckmann** [comment]
I found the exact same files under ~/.virtualenvs/eclink_env/lib/python3.4/site-packages/djangocms_video/templates/djangocms_video/default

But I do have aldryn-video==1.0.0 installed. Could that be interfering?

**Comment by FinalAngel** [comment]
@maltebeckmann not seing swfobject being used in aldryn-video

**Comment by maltebeckmann** [comment]
I commented out cmsplugin_filer_video and that seems to have removed the old template stuff.

However, now I am getting a message in Chrome dev tools saying: 

Resource interpreted as Document but transferred with MIME type application/x-shockwave-flash: "http://static.youku.com/v1.0.0684/v/swf/loader.swf?VideoIDS=XNDYwMTEzMTY0&w…526type%253D0%2526embsig%253D1_1484560838_a7115a5e0c44e085f42b23528b438d5f".

**Comment by FinalAngel** [comment]
yeah thats something that comes from youku directly, the only alternative there would be to use their api and rewrite the frontend of djangocms-video to use that.

Closing now :)
