### ISSUE TITLE
aldryn_search indexing incompatibility

### ISSUE THREAD

**Issue by SteinRobert** [divio/djangocms-video#31]
As aldryn_search is trying to index the contents of every plugin the `VideoSourcePlugin` (and I suppose it's the same with the `VideoTrackPlugin`) breaks when trying to publish a page. 
Both plugins are trying to access the template through the context in the `get_render_template` method which does not work when a page is published and aldryn_search is trying to render it.
Line in the plugin:
https://github.com/divio/djangocms-video/blob/master/djangocms_video/cms_plugins.py#L72
Line in aldryn_search:
https://github.com/aldryn/aldryn-search/blob/master/aldryn_search/helpers.py#L48

If I got the problem right I guess it would help to add `search_fields` to the models.

**Comment by FinalAngel** [comment]
@SteinRobert thank you very much for the report, would you be able to propose a pull request and test it if that solved your problem?

**Comment by SteinRobert** [comment]
I think we should resolve this issue first: aldryn/aldryn-search#73.
Having done that, this should be fine too.
