### ISSUE TITLE
It's quite hard to embed a YouTube video

### ISSUE THREAD

**Issue by boterpoes** [divio/djangocms-video#32]
The steps required for an end-user to actually embed a YouTube video seem quite hard:

- Find the video on YouTube
- Click on 'share'
- Go to the 'embed' tab
- Extract the 'src' attribute from the generated iframe code

Especially the last step is in my opinion way too hard for the average user.

My suggestion would be to either extract the src attribute if the whole iframe code is pasted into the embed field, or even better, to accept the URL of the video (in the format https://www.youtube.com/watch?v=XXXXXXXXXXX) and convert that to an embed link.

If I remember correctly, Django Embed Video uses the last option, which IMHO greatly enhances usability.

**Comment by FinalAngel** [comment]
@boterpoes thank you for your request. The goal of djangocms-video is to allow embedding of video services such as youtube, wistia, sprout etc. all together. We do not intend to built in a functionality to automatically convert a specific URL from a video service at this moment.

We would suggest to create a specific addon that extends this one to achieve your goal or have a look at https://github.com/mishbahr/djangocms-youtube and similar.

**Comment by vxsx** [comment]
What also worked well enough for me was adapting the template so the embed link looks like this:
```django
https://youtube.com/embed/{{ instance.embed_link|cut:'https://www.youtube.com/embed/'|cut:'https://www.youtube.com/watch?v=' }}
```

**Comment by boterpoes** [comment]
Allright, thanks @FinalAngel for your reply, and thanks for the suggestiong @vxsx, I'll give it a try.
