### ISSUE TITLE
Adding source files when using the Text CKEditor plugin.

### ISSUE THREAD

**Issue by bluegrounds** [divio/djangocms-video#38]
When using the "Video plugin" inside djangocms-text-ckeditor, there's no way to add a source from a child source plugin like how it is when using the plugin in Structure mode.
[Pictures](https://imgur.com/a/ry4vD)

**Comment by tristant** [comment]
Confirming the issue, very problematic since CKEditor is the default for Django-CMS

**Comment by vxsx** [comment]
I understand the pain, but currently it is impossible to add child plugins to children of TextPlugin, as there are _lots_ of limitations to them. You might want to use video plugin outside of the TextPlugin in this case.

We have no plans to add this possibility for the moment.

**Comment by bluegrounds** [comment]
Oh, I see. Thanks.
