### ISSUE TITLE
Can't play video from vimeo

### ISSUE THREAD

**Issue by mihi-tr** [divio/djangocms-video#4]
The plugin doesn't play videos from vimeo the address http://bitcast.vimeo.com/vimeo/swf/moogaloop.swf does not seem to exist anymore. (404)

**Comment by FinalAngel** [comment]
hello @mihi-tr, this is due to the fact that ``player.swf`` refers to ``bitcast.vimeo`` while the new url is something like ``http://vimeo.com/moogaloop.swf?clip_id=2539741``. While noone of us can edit the player.swf, I'd recommend waiting for the 2.0 upgrade to HTML5.

**Comment by FinalAngel** [comment]
Will be fixed in https://github.com/divio/djangocms-video/pull/21
