### ISSUE TITLE
By default the player has minimal size, eg 100x100 pixels, and editors don't know how to fix it

### ISSUE THREAD

**Issue by victor-yunenko** [divio/djangocms-video#57]
For example:

![Pasted_Image_20-Apr-04__21_02](https://user-images.githubusercontent.com/36416236/78458122-ac4c5d80-76b7-11ea-822a-115a7d322000.png)

It can be fixed by adding custom attributes `width` & `height`, but it isn't something an editor not familiar with HTML can do.

There's a css fix:
```
.djangocms-video-plugin {
    position: relative;
    padding-bottom: 56.25%;
    padding-top: 30px;
    height: 0;
    overflow: hidden;
    
    iframe, object, embed {
        position: absolute;
        top: 0;
        left: 0;
        width: 100%;
        height: 100%;
    }
}
```

**Comment by FinalAngel** [comment]
For now rejected as per #57
